### ISSUE TITLE
Make separate footprint repo

### ISSUE THREAD

**Issue by alexanderhiam** [graycatlabs/OSD335x-KiCad#3]
The footprint should probably be moved to a proper `OSD3358.pretty` repo.

@angst7: do you have a preference as to where it lives? I could create `graycatlabs/OSD3358.pretty` if you don't mind that existing under the Gray Cat Labs name (with you as a member of the repo and credited as making it of course), or somewhere else is fine with me.

**Comment by angst7** [comment]
I don't mind that at all.  Go for it.

**Comment by alexanderhiam** [comment]
https://github.com/graycatlabs/OSD335x.pretty
