### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alexanderhiam** [graycatlabs/OSD335x-KiCad#4]
Should this continue to exist in the public domain, or under a FOSS license? 

Does this count as a derivative of Octavo's OrCAD symbol? If so what's the license on that?

Need to think about all that boring stuff...

**Comment by angst7** [comment]
I'll contact them to see if they have any license requirements/restrictions on the use of the .csv file for generation libraries for other EDA packages.

**Comment by angst7** [comment]
Octavo replied with the following: 

> Thanks for the interest in the OSD3358 and your desire to create a KiCad file for it.  There are no restrictions on the csv file.  The more people that can use the symbol the better.

So I think public domain or maybe CC By 3.0 would be fine.

**Comment by alexanderhiam** [comment]
Awesome. CC BY 3.0 seems good to me. 

I often use CC BY-SA, but I guess the SA could mean any schematics using the part would also need to be CC? Or would it fall under a libraries kind of thing in that case?

**Comment by angst7** [comment]
I don't know, tbh.   I've avoided SA for that reason, but I'm not really clear on all the details.

**Comment by alexanderhiam** [comment]
OK, CC BY 3.0 it is
