### ISSUE TITLE
NC and Reserved pins

### ISSUE THREAD

**Issue by angst7** [graycatlabs/OSD335x-KiCad#5]
I've gone through and marked the NC pins as no_connect as per the datasheet, but there are also a set of reserved pins that the data sheet says should not be used externally to the device.  Think I should just mark them no_connect as well?

**Comment by alexanderhiam** [comment]
Yeah, I think that makes sense, the ERC should yell at you if you try to use them in that case.

FYI I added you to the repos, so you should be able to push directly instead of needing a pull request.

**Comment by angst7** [comment]
Oh, that makes things easier.  Thanks!
